# Site settings
title: Hujeery Blog
email: hujeery@gmail.com
description: Hujeery Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hujeery.github.io" # the base hostname & protocol for your site
twitter_username: hujeery
github_username: hujeery

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
